# Generated by Django 3.2 on 2024-11-01 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_alter_jugador_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='estadio',
            field=models.CharField(default='Estadio desconocido', max_length=255),
        ),
        migrations.AddField(
            model_name='partido',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='partido',
            name='hora',
            field=models.IntegerField(default=0),
        ),
    ]
