# Generated by Django 3.2 on 2024-11-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_jugador_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(choices=[('PG', 'Base (Point Guard)'), ('SG', 'Escolta (Shooting Guard)'), ('SF', 'Alero (Small Forward)'), ('PF', 'Ala-Pivot (Power Forward)'), ('C', 'Pivot (Center)')], default='PG', max_length=2),
        ),
    ]
