# Generated by Django 3.2 on 2024-11-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0006_alter_jugador_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='conferencia',
            field=models.CharField(choices=[('E', 'ESTE'), ('W', 'OESTE')], default='E', max_length=2),
        ),
    ]
