# Generated by Django 3.2 on 2024-11-02 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0007_alter_equipo_conferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
