# Generated by Django 3.2 on 2024-11-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0009_partido_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
    ]
