# Generated by Django 3.2 on 2024-11-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0010_empleado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
