# Generated by Django 3.2 on 2024-11-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0012_alter_jugador_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
